// Crearé un array de objetos de verbos regulares e irregulares

let irregular=[

    arise={
        infinitivo:"Arise",
        pasado:"Arose",
        participio:"Arisen",
        significado:"Surgir, Levantarse",
        imagen:"ruta",
    },

    awake={
        infinitivo:"Awake",
        pasado:"Awoke",
        participio:"Awaken",
        significado:"Despertarse",
        imagen:"ruta",
    },

    be={
        infinitivo:"Be / (am/is/are)",
        pasado:"Was / were",
        participio:"Been",
        significado:"Ser / estar",
        imagen:"ruta"
    },

    bear={
        infinitivo:"Bear",
        pasado:"Bore"
        participio:"Borne / born"
        significado:"Soportar / dar a luz"
        imagen:
    }

    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }
    arise={
        infinitivo:""
        pasado:
        participio:
        significado:
        imagen:
    }



]